/**
 * Incremental file-delta writer over the derived SQLite store.
 *
 * Ported from the reference implementation's file-batch writers
 * (`cc-db/src/index_db_write_batch.rs`). Every delta commits as exactly one
 * {@link ./epoch.ts!bumpIndexEpochOnceInTx | epoch-bumped} transaction:
 * per-path FTS-mirror deletes resolve doomed rowids through the still-present
 * base rows and run BEFORE the base deletes, chunk insertion mirrors plain
 * text into `chunks_fts` under the base row's own rowid, optional per-file
 * graph rows (`symbols` / `imports` / `symbol_refs` / `call_edges` /
 * `test_edges` / `literal_index`) ride the same delete-then-insert cycle, and
 * the whole unit rolls back atomically on any failure.
 *
 * @module @relay-harness/rlh-code-index-sqlite/writer
 */

import type { DatabaseSync } from 'node:sqlite'
import type { ParserTier } from '@relay-harness/rlh-code-index'
import {
  CodeIndexError,
  CODE_INDEX_VECTOR_ROW_INVALID,
} from '@relay-harness/rlh-code-index'
import { bumpEmbeddingEpochOnceInTx, bumpIndexEpochOnceInTx } from './epoch.ts'
import { encodeChunkText } from './codec.ts'
import { CODE_INDEX_METADATA_EXPORT_FINGERPRINT_PREFIX } from './ddl.ts'

/**
 * Chunk size for batched `IN (...)` statements, ported from the reference
 * implementation (`IN_BATCH_SIZE`) to respect `SQLITE_MAX_VARIABLE_NUMBER`.
 */
const SQL_IN_BATCH_SIZE = 200

/** One chunk of an upserted file, in provider-parse order (matches `chunk_index`). */
export interface ChunkUpsert {
  /** Stable identity following the `chunk:<file_path>:<chunk_index>` layout. */
  readonly chunkId: string
  /** Zero-based position of this chunk within its file. */
  readonly chunkIndex: number
  /** Inclusive start line (1-based). */
  readonly startLine: number
  /** Inclusive end line (1-based). */
  readonly endLine: number
  /** Enclosing declaration path from the parser; `''` when unknown. */
  readonly breadcrumb: string
  /** Nearest enclosing symbol name, or `null` when none was extracted. */
  readonly symbolName: string | null
  /** Parser symbol kind tag, or `null` when no symbol was extracted. */
  readonly symbolKind: string | null
  /** Decoded chunk text; stored via the codec and mirrored plain into FTS. */
  readonly text: string
  /** Cheap token-count estimate used for output budgeting upstream. */
  readonly tokenEstimate: number
}

/** One file's parsed payload as the provider submits it to storage. */
export interface FileUpsert {
  /** Workspace-relative path; primary key of the `files` row. */
  readonly filePath: string
  /** Language name stored on the file row; readers join it onto chunks. */
  readonly language: string
  /** Content hash identifying the parsed revision. */
  readonly contentHash: string
  /** File mtime at scan time (seconds since epoch, fractional). */
  readonly mtime: number
  /** File size in bytes at scan time. */
  readonly size: number
  /** Model-facing summary generated by the caller; mirrored into `files_fts`. */
  readonly summary: string
  /** Head-of-content excerpt generated by the caller; mirrored into `files_fts`. */
  readonly contentExcerpt: string
  /** Extraction tier that produced the chunks. */
  readonly parserTier: ParserTier
  /** Confidence reported alongside {@link FileUpsert.parserTier}. */
  readonly parserConfidence: number
  /** Whether the file is a test source; feeds ranking bonuses upstream. */
  readonly isTestFile: boolean
  /** The file's chunks, replacing whatever previous chunks existed for the path. */
  readonly chunks: readonly ChunkUpsert[]
}

/** One `symbols` row; every field binds 1:1 to its column, `null` meaning SQL NULL. */
export interface SymbolRowInput {
  readonly symbolId: string
  readonly filePath: string
  readonly name: string
  readonly kind: string
  readonly container: string | null
  readonly startLine: number
  readonly endLine: number
  readonly startCol: number | null
  readonly endCol: number | null
  readonly signature: string | null
  readonly doc: string | null
  readonly parserTier: ParserTier | null
  readonly parserConfidence: number | null
  readonly qname: string | null
  readonly parentSymbolId: string | null
  readonly exportName: string | null
  readonly isDefaultExport: boolean
  /** Store-global symbol identity; `null` rows are unreachable by uid lookups. */
  readonly symbolUid: string | null
  readonly frameworkRole: string | null
  readonly receiverType: string | null
  readonly paramTypes: string | null
  readonly returnType: string | null
  readonly paramCount: number | null
  readonly baseTypes: string | null
  readonly implements: string | null
}

/** One `imports` row; `rowid` is assigned by SQLite. */
export interface ImportRowInput {
  readonly filePath: string
  readonly importString: string
  readonly resolvedPath: string | null
  readonly importedName: string | null
  readonly alias: string | null
  readonly isNamespace: boolean
  readonly isDefault: boolean
  readonly isReexport: boolean
}

/** One `symbol_refs` row. */
export interface SymbolRefRowInput {
  readonly refId: string
  readonly filePath: string
  readonly symbolName: string | null
  readonly container: string | null
  readonly refKind: string | null
  readonly line: number | null
  readonly col: number | null
  readonly targetSymbolId: string | null
  readonly targetFilePath: string | null
  readonly targetSymbolUid: string | null
  readonly refName: string | null
  readonly resolutionKind: string | null
  readonly resolutionConfidence: number | null
  readonly resolutionStrategy: string | null
  readonly parserTier: ParserTier | null
  readonly parserConfidence: number | null
}

/** One `call_edges` row. */
export interface CallEdgeRowInput {
  readonly edgeId: string
  readonly filePath: string
  readonly callerSymbol: string | null
  readonly calleeSymbol: string | null
  readonly line: number | null
  readonly startCol: number | null
  readonly targetSymbolId: string | null
  readonly targetFilePath: string | null
  readonly callerSymbolId: string | null
  readonly callerSymbolUid: string | null
  readonly calleeSymbolUid: string | null
  readonly dispatchKind: string | null
  readonly callKind: string | null
  readonly resolutionKind: string | null
  readonly resolutionConfidence: number | null
  readonly resolutionStrategy: string | null
  readonly receiverExpr: string | null
  readonly argCount: number | null
  readonly isOptionalChain: boolean
  readonly isAwaited: boolean
  readonly isConstructor: boolean
  readonly parserTier: ParserTier | null
  readonly parserConfidence: number | null
}

/** One `test_edges` row; test/code paths are plain paths, not foreign keys. */
export interface TestEdgeRowInput {
  readonly edgeId: string
  readonly testFilePath: string
  readonly codeFilePath: string
  readonly reason: string | null
  readonly confidence: number | null
}

/** One `literal_index` row. */
export interface LiteralRowInput {
  readonly literalId: string
  readonly filePath: string
  readonly literal: string | null
  readonly literalKind: string | null
  readonly line: number | null
  readonly container: string | null
  readonly confidence: number | null
  readonly enclosingSymbolUid: string | null
}

/** Graph rows belonging to one upserted file, in provider-parse order. */
export interface FileGraphDelta {
  readonly symbols: readonly SymbolRowInput[]
  readonly imports: readonly ImportRowInput[]
  readonly callEdges: readonly CallEdgeRowInput[]
  readonly symbolRefs: readonly SymbolRefRowInput[]
  readonly testEdges: readonly TestEdgeRowInput[]
  readonly literals: readonly LiteralRowInput[]
  /**
   * Export surface hash recorded under `export_fingerprint:<filePath>` in the
   * metadata ledger. A string replaces the previous value on every upsert;
   * `null` clears the ledger entry (the file's export surface became empty),
   * and `undefined` leaves any stored value untouched.
   */
  readonly exportFingerprint?: string | null
}

/**
 * Graph half of a delta, keyed by upserted file path (Map or plain record).
 * Only entries whose key matches an upserted path are written; the delete pass
 * has already removed that path's previous graph rows.
 */
export interface GraphDeltaInput {
  readonly byFile: ReadonlyMap<string, FileGraphDelta> | Record<string, FileGraphDelta>
}

/**
 * One committed write unit: paths to remove entirely plus files to upsert.
 * A path listed in both halves deletes once through the removal pass, then
 * re-inserts — repeating a path inside either half alone violates a primary
 * key and rolls the whole delta back.
 */
export interface FilesDelta {
  /** Paths whose rows (base + every mirror) disappear from the store. */
  readonly removals: readonly string[]
  /** Files to delete-then-reinsert with their current chunk lists. */
  readonly upserts: readonly FileUpsert[]
  /** Optional per-file graph rows written alongside each upsert's chunks. */
  readonly graph?: GraphDeltaInput
}

/** Counts reported by one committed {@link writeFilesDelta} call. */
export interface FilesDeltaResult {
  /** Files removed through the delta's removal half (replaced paths excluded). */
  readonly removedFiles: number
  /** Files inserted by the upsert half (one row each). */
  readonly upsertedFiles: number
  /** Chunk rows written across all upserted files. */
  readonly chunksWritten: number
  /** Symbol rows written across all upserted files. */
  readonly symbolsWritten: number
  /** Call-edge plus symbol-reference rows written across all upserted files. */
  readonly edgesWritten: number
  /** Test-edge rows written across all upserted files. */
  readonly testEdgesWritten: number
  /** Literal rows written across all upserted files. */
  readonly literalsWritten: number
}

/** Options for {@link writeFilesDelta}. */
export interface WriteFilesDeltaOptions {
  /**
   * Wall-clock source stamping `files.indexed_at`; defaults to UTC now.
   * Injection exists so recency-ordered reads can be tested deterministically.
   */
  readonly now?: () => string
}

/**
 * Commit one file delta: removal pass first, then per-file delete-then-insert
 * (chunks plus optional graph rows), all inside a single index-epoch-bumped
 * transaction.
 *
 * Deletion order follows the reference implementation's app-maintained FTS
 * rule: `file_paths_fts` and `symbols_fts` heal themselves through triggers
 * (explicit `symbols` deletes therefore run first, and the FK's cascaded
 * second delete removes zero rows — never a double delete), while `chunks_fts`
 * and `files_fts` must be deleted BY ROWID through their base tables before
 * those base rows disappear, then re-mirrored after insertion.
 * @param db - admitted handle; must not have another transaction open.
 * @param delta - removals plus upserts, with unique paths within each half.
 * @param options - clock injection for `indexed_at`.
 * @returns what changed, observable only after the COMMIT succeeded.
 * @throws Any statement failure aborts the whole delta: nothing persists and
 *   the index epoch does not move (see {@link bumpIndexEpochOnceInTx}).
 */
export function writeFilesDelta(
  db: DatabaseSync,
  delta: FilesDelta,
  options: WriteFilesDeltaOptions = {},
): FilesDeltaResult {
  const now = options.now ?? (() => new Date().toISOString())
  return bumpIndexEpochOnceInTx(db, () => {
    let removedFiles = 0
    let chunksWritten = 0
    let symbolsWritten = 0
    let edgesWritten = 0
    let testEdgesWritten = 0
    let literalsWritten = 0
    for (const batch of inBatches(delta.removals)) {
      removedFiles += deleteFileRows(db, batch)
    }
    // Upserted paths delete-then-reinsert here; their deletions never count
    // toward removedFiles because the row comes back within this same commit.
    for (const file of delta.upserts) {
      deleteFileRows(db, [file.filePath])
      const graph = graphDeltaFor(delta.graph, file.filePath)
      insertFileUpsert(db, file, now())
      if (graph !== undefined) {
        const counts = insertFileGraph(db, graph)
        symbolsWritten += counts.symbols
        edgesWritten += counts.callEdges + counts.symbolRefs
        testEdgesWritten += counts.testEdges
        literalsWritten += counts.literals
        if (graph.exportFingerprint !== undefined) {
          if (graph.exportFingerprint === null) {
            db.prepare('DELETE FROM metadata WHERE key = ?').run(
              `${CODE_INDEX_METADATA_EXPORT_FINGERPRINT_PREFIX}${file.filePath}`,
            )
          } else {
            db.prepare('INSERT OR REPLACE INTO metadata (key, value) VALUES (?, ?)').run(
              `${CODE_INDEX_METADATA_EXPORT_FINGERPRINT_PREFIX}${file.filePath}`,
              graph.exportFingerprint,
            )
          }
        }
      }
      chunksWritten += file.chunks.length
    }
    return {
      removedFiles,
      upsertedFiles: delta.upserts.length,
      chunksWritten,
      symbolsWritten,
      edgesWritten,
      testEdgesWritten,
      literalsWritten,
    } satisfies FilesDeltaResult
  })
}

/**
 * One file's resolved edge rows for {@link writeResolvedEdges}: the complete
 * replacement row sets per category. An omitted category means "no rows for
 * this file" — its previous rows are still deleted, so absent and empty are
 * the same replacement.
 */
export interface ResolvedEdgeFileUpdate {
  /** Workspace-relative path whose edge rows this update replaces. */
  readonly filePath: string
  /** The file's complete `call_edges` row set, resolution targets included. */
  readonly callEdges?: readonly CallEdgeRowInput[]
  /** The file's complete `symbol_refs` row set, resolution targets included. */
  readonly symbolRefs?: readonly SymbolRefRowInput[]
}

/** Counts reported by one committed {@link writeResolvedEdges} call. */
export interface WriteResolvedEdgesResult {
  /** Per-file replace cycles performed (one per entry in `updates`). */
  readonly filesTouched: number
  /** Call-edge rows written across all updates. */
  readonly callEdgesWritten: number
  /** Symbol-ref rows written across all updates. */
  readonly symbolRefsWritten: number
}

/**
 * Replace the `call_edges` and `symbol_refs` rows of the given files with the
 * provided resolved row sets, inside one index-epoch-bumped transaction.
 *
 * This is the dirty-reresolve write face, mirroring the reference
 * implementation's `replace_reresolved_edges_only` Keep/Clear split: only the
 * two resolver-owned tables are deleted and re-inserted, while `files`,
 * `chunks`, the FTS mirrors, `symbols`, `imports`, and `test_edges` stay
 * untouched — `symbols` / `imports` carry no cross-file resolution state (the
 * reference's `KeepAsIs`) and are maintained by the full delta path, and
 * `test_edges` are path-pair rows rebuilt through the test-edge rebuilds.
 * Each row keeps its own `filePath` column value, so callers must not spread
 * one file's rows across entries (the delete pass would not visit them).
 * @param db - admitted handle; must not have another transaction open.
 * @param updates - one entry per file, unique paths; every entry deletes both
 *   tables for its path before re-inserting the provided rows.
 * @returns what changed, observable only after the COMMIT succeeded.
 * @throws Any statement failure aborts the whole call — including a foreign
 *   key violation for a path without a `files` row, which leaves the previous
 *   edges in place and the index epoch unmoved.
 */
export function writeResolvedEdges(
  db: DatabaseSync,
  updates: readonly ResolvedEdgeFileUpdate[],
): WriteResolvedEdgesResult {
  return bumpIndexEpochOnceInTx(db, () => {
    const deleteCallEdges = db.prepare('DELETE FROM call_edges WHERE file_path = ?')
    const deleteRefs = db.prepare('DELETE FROM symbol_refs WHERE file_path = ?')
    const insertCallEdge = db.prepare(`
      INSERT INTO call_edges (
        edge_id, file_path, caller_symbol, callee_symbol, line, start_col,
        target_symbol_id, target_file_path, caller_symbol_id, caller_symbol_uid,
        callee_symbol_uid, dispatch_kind, call_kind, resolution_kind,
        resolution_confidence, resolution_strategy, receiver_expr, arg_count,
        is_optional_chain, is_awaited, is_constructor, parser_tier, parser_confidence
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `)
    const insertRef = db.prepare(`
      INSERT INTO symbol_refs (
        ref_id, file_path, symbol_name, container, ref_kind, line, col,
        target_symbol_id, target_file_path, target_symbol_uid, ref_name,
        resolution_kind, resolution_confidence, resolution_strategy,
        parser_tier, parser_confidence
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `)
    let callEdgesWritten = 0
    let symbolRefsWritten = 0
    for (const update of updates) {
      deleteCallEdges.run(update.filePath)
      deleteRefs.run(update.filePath)
      for (const row of update.callEdges ?? []) {
        runInsertCallEdge(insertCallEdge, row)
        callEdgesWritten += 1
      }
      for (const row of update.symbolRefs ?? []) {
        runInsertRef(insertRef, row)
        symbolRefsWritten += 1
      }
    }
    return {
      filesTouched: updates.length,
      callEdgesWritten,
      symbolRefsWritten,
    } satisfies WriteResolvedEdgesResult
  })
}

/**
 * One `chunks_vec` row as the embedding drain submits it. `q` is the byte view
 * `new Uint8Array(int8Array.buffer)` of the quantized components (one byte per
 * dimension — the search package's vector-math storage contract); `scale`,
 * `norm`, and `dim` travel as their own scalar columns, never through the BLOB.
 */
export interface ChunkVectorRowInput {
  /** Chunk the vector belongs to; must reference an existing `chunks` row. */
  readonly chunkId: string
  /** Denormalized `chunks.rowid` captured when the chunk row was read. */
  readonly chunkRowid: number
  /** Complete embedding-pipeline generation identity; half the durable row key. */
  readonly generationId?: string
  /**
   * Embedding model identity; half the row key. Vectors of different models
   * for the same chunk coexist as sibling rows.
   */
  readonly model: string
  /** Component count; must equal `q.byteLength` for one-byte int8 elements. */
  readonly dim: number
  /** Dequantization multiplier from the quantization record. */
  readonly scale: number
  /** Byte view of the signed int8 components. */
  readonly q: Uint8Array
  /** ORIGINAL float norm captured before quantization. */
  readonly norm: number
}

/** Counts reported by one committed {@link writeChunkVectors} call. */
export interface WriteChunkVectorsResult {
  /** Vector rows written (one per input). */
  readonly vectorsWritten: number
}

/**
 * Commit a batch of chunk vectors inside one embedding-epoch-bumped
 * transaction. Re-embedding an existing `(chunk_id, generation_id)` pair
 * replaces exactly that pair's row; other generations remain untouched.
 *
 * The embedding drain calls this once per processed job, which is the
 * evidence tier's per-commit granularity: N drained jobs advance the clock
 * exactly N times.
 * @param db - admitted handle; must not have another transaction open.
 * @param rows - vector rows to upsert; a chunk id without a `chunks` row
 *   violates the foreign key and aborts the whole batch.
 * @returns what changed, observable only after the COMMIT succeeded.
 * @throws {CodeIndexError} with `CODE_INDEX_VECTOR_ROW_INVALID` when a row's
 *   `q.byteLength` contradicts its `dim` — the search lane reads rows by
 *   component count, so a mismatched pair would poison ranking.
 * @throws Any statement failure aborts the whole batch: nothing persists and
 *   the evidence epoch does not move.
 */
export function writeChunkVectors(
  db: DatabaseSync,
  rows: readonly ChunkVectorRowInput[],
): WriteChunkVectorsResult {
  return bumpEmbeddingEpochOnceInTx(db, () => {
    const insert = db.prepare(`
      INSERT OR REPLACE INTO chunks_vec (
        chunk_id, chunk_rowid, generation_id, model, dim, format, scale, q, norm
      ) VALUES (?, ?, ?, ?, ?, 'int8', ?, ?, ?)
    `)
    for (const row of rows) {
      if (row.q.byteLength !== row.dim) {
        throw new CodeIndexError(
          `chunk vector row for ${row.chunkId} (model ${row.model}) declares dim ${row.dim} `
            + `but its byte view carries ${row.q.byteLength} bytes`,
          CODE_INDEX_VECTOR_ROW_INVALID,
        )
      }
      const generationId = row.generationId ?? ensureLegacyVectorGeneration(db, row.model)
      insert.run(row.chunkId, row.chunkRowid, generationId, row.model, row.dim, row.scale, row.q, row.norm)
    }
    return { vectorsWritten: rows.length } satisfies WriteChunkVectorsResult
  })
}

function ensureLegacyVectorGeneration(db: DatabaseSync, model: string): string {
  const generationId = `legacy-model:${model}`
  db.prepare(`
    INSERT OR IGNORE INTO embedding_generations (
      generation_id, provider_id, endpoint_identity, model,
      configured_dimensions, dimension_mode, normalization_version,
      quantizer_version, chunker_version, created_at
    ) VALUES (?, 'legacy-direct-store', 'legacy:', ?, NULL, 'provider-default',
      'legacy', 'legacy', 'legacy', ?)
  `).run(generationId, model, new Date().toISOString())
  return generationId
}

/** Split a path list into SQL-variable-sized batches for `IN (...)` statements. */
function* inBatches(paths: readonly string[]): Generator<readonly string[]> {
  for (let start = 0; start < paths.length; start += SQL_IN_BATCH_SIZE) {
    yield paths.slice(start, start + SQL_IN_BATCH_SIZE)
  }
}

/** Render `?` placeholders matching a batch length for positional binding. */
function placeholders(count: number): string {
  return Array.from({ length: count }, () => '?').join(', ')
}

// Application-maintained mirrors only: `file_paths_fts` and `symbols_fts`
// keep themselves aligned through schema triggers fired by the base-table
// DELETEs below.
const APP_MAINTAINED_FTS: ReadonlyArray<readonly [ftsTable: string, baseTable: string]> = [
  ['chunks_fts', 'chunks'],
  ['files_fts', 'files'],
]

/** Per-file graph-row child tables deleted explicitly ahead of their files rows. */
const GRAPH_CHILD_TABLES: readonly string[] = [
  'imports',
  'symbol_refs',
  'call_edges',
  'literal_index',
]

/**
 * Look up one file's graph rows in either accepted byFile container form.
 * @param graph - the delta's graph half, or `undefined`.
 * @param filePath - upserted path whose rows to fetch.
 * @returns the file's graph rows, or `undefined` when absent.
 */
function graphDeltaFor(
  graph: GraphDeltaInput | undefined,
  filePath: string,
): FileGraphDelta | undefined {
  if (graph === undefined) return undefined
  if (graph.byFile instanceof Map) {
    return (graph.byFile as ReadonlyMap<string, FileGraphDelta | undefined>).get(filePath)
  }
  return (graph.byFile as Record<string, FileGraphDelta | undefined>)[filePath]
}

/**
 * Delete every row a set of file paths owns. Must run while the base rows are
 * alive: the rowid-aligned mirror deletes resolve rowids through them. Graph
 * child rows go first (explicitly — the FK would cascade them anyway, but the
 * symbols delete fires the `symbols_fts` triggers exactly once per doomed row,
 * and the later cascaded delete finds nothing left to remove), then the
 * per-file export-fingerprint ledger entry, then the mirrors and base rows.
 * @returns how many `files` rows disappeared (0 for unknown paths).
 */
function deleteFileRows(db: DatabaseSync, paths: readonly string[]): number {
  const bind: Array<string> = [...paths]
  for (const table of GRAPH_CHILD_TABLES) {
    db.prepare(
      `DELETE FROM ${table} WHERE file_path IN (${placeholders(bind.length)})`,
    ).run(...bind)
  }
  db.prepare(
    `DELETE FROM symbols WHERE file_path IN (${placeholders(bind.length)})`,
  ).run(...bind)
  const fingerprintKeys = bind.map(path => `${CODE_INDEX_METADATA_EXPORT_FINGERPRINT_PREFIX}${path}`)
  db.prepare(
    `DELETE FROM metadata WHERE key IN (${placeholders(fingerprintKeys.length)})`,
  ).run(...fingerprintKeys)
  for (const [ftsTable, baseTable] of APP_MAINTAINED_FTS) {
    db.prepare(
      `DELETE FROM ${ftsTable} WHERE rowid IN `
      + `(SELECT rowid FROM ${baseTable} WHERE file_path IN (${placeholders(bind.length)}))`,
    ).run(...bind)
  }
  const result = db.prepare(
    `DELETE FROM files WHERE file_path IN (${placeholders(bind.length)})`,
  ).run(...bind)
  return Number(result.changes)
}

/**
 * Insert one file row and its plain-text `files_fts` mirror under the same
 * rowid, then each chunk row followed immediately by its `chunks_fts` mirror.
 * The chunk row stores the codec's `(encoding, payload)` pair while the FTS
 * mirror always receives the decoded text — search matches plaintext no
 * matter how the base row is stored. `lastInsertRowid` of a completed INSERT
 * names that outermost statement's row even across trigger inserts, so
 * mirror alignment needs no subselects.
 */
function insertFileUpsert(db: DatabaseSync, file: FileUpsert, indexedAt: string): void {
  const insertFile = db.prepare(`
    INSERT INTO files (
      file_path, language, content_hash, mtime, size, summary, content_excerpt,
      parser_tier, parser_confidence, is_test_file, indexed_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `)
  const insertFileFts = db.prepare(
    'INSERT INTO files_fts (rowid, file_path, summary, content_excerpt) VALUES (?, ?, ?, ?)',
  )
  const insertChunk = db.prepare(`
    INSERT INTO chunks (
      chunk_id, file_path, chunk_index, start_line, end_line,
      breadcrumb, symbol_name, symbol_kind, text, text_encoding, token_estimate
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `)
  const insertChunkFts = db.prepare(
    'INSERT INTO chunks_fts (rowid, breadcrumb, symbol_name, text) VALUES (?, ?, ?, ?)',
  )
  const { lastInsertRowid: fileRowid } = insertFile.run(
    file.filePath,
    file.language,
    file.contentHash,
    file.mtime,
    file.size,
    file.summary,
    file.contentExcerpt,
    file.parserTier,
    file.parserConfidence,
    file.isTestFile ? 1 : 0,
    indexedAt,
  )
  insertFileFts.run(fileRowid, file.filePath, file.summary, file.contentExcerpt)
  for (const chunk of file.chunks) {
    const encoded = encodeChunkText(chunk.text)
    const { lastInsertRowid: chunkRowid } = insertChunk.run(
      chunk.chunkId,
      file.filePath,
      chunk.chunkIndex,
      chunk.startLine,
      chunk.endLine,
      chunk.breadcrumb,
      chunk.symbolName,
      chunk.symbolKind,
      encoded.payload,
      encoded.encoding,
      chunk.tokenEstimate,
    )
    insertChunkFts.run(chunkRowid, chunk.breadcrumb, chunk.symbolName, chunk.text)
  }
}

/** How many rows one file's graph half wrote, per table family. */
interface FileGraphWriteCounts {
  readonly symbols: number
  readonly callEdges: number
  readonly symbolRefs: number
  readonly testEdges: number
  readonly literals: number
}


/** Prepared-statement type shared by the writer's INSERT binders. */
type PreparedInsert = ReturnType<DatabaseSync['prepare']>

/**
 * Bind one call-edge row to its INSERT; the 23-column order is the single
 * source of truth for both the delta path and the resolved-edge write face.
 */
function runInsertCallEdge(insertCallEdge: PreparedInsert, row: CallEdgeRowInput): void {
  insertCallEdge.run(
    row.edgeId,
    row.filePath,
    row.callerSymbol,
    row.calleeSymbol,
    row.line,
    row.startCol,
    row.targetSymbolId,
    row.targetFilePath,
    row.callerSymbolId,
    row.callerSymbolUid,
    row.calleeSymbolUid,
    row.dispatchKind,
    row.callKind,
    row.resolutionKind,
    row.resolutionConfidence,
    row.resolutionStrategy,
    row.receiverExpr,
    row.argCount,
    row.isOptionalChain ? 1 : 0,
    row.isAwaited ? 1 : 0,
    row.isConstructor ? 1 : 0,
    row.parserTier,
    row.parserConfidence,
  )
}

/**
 * Bind one symbol-ref row to its INSERT; the 16-column order is the single
 * source of truth for both the delta path and the resolved-edge write face.
 */
function runInsertRef(insertRef: PreparedInsert, row: SymbolRefRowInput): void {
  insertRef.run(
    row.refId,
    row.filePath,
    row.symbolName,
    row.container,
    row.refKind,
    row.line,
    row.col,
    row.targetSymbolId,
    row.targetFilePath,
    row.targetSymbolUid,
    row.refName,
    row.resolutionKind,
    row.resolutionConfidence,
    row.resolutionStrategy,
    row.parserTier,
    row.parserConfidence,
  )
}

/**
 * Insert one file's graph rows. `symbols` inserts fire the `symbols_fts`
 * triggers, which maintain the trigram mirror without writer statements; the
 * remaining tables are plain app-maintained rows.
 * @param db - admitted handle inside the open delta transaction.
 * @param graph - the file's graph rows.
 * @returns per-family row counts for the delta result.
 */
function insertFileGraph(db: DatabaseSync, graph: FileGraphDelta): FileGraphWriteCounts {
  const insertSymbol = db.prepare(`
    INSERT INTO symbols (
      symbol_id, file_path, name, kind, container, start_line, end_line,
      start_col, end_col, signature, doc, parser_tier, parser_confidence,
      qname, parent_symbol_id, export_name, is_default_export, symbol_uid,
      framework_role, receiver_type, param_types, return_type, param_count,
      base_types, implements
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `)
  const insertImport = db.prepare(`
    INSERT INTO imports (
      file_path, import_string, resolved_path, imported_name, alias,
      is_namespace, is_default, is_reexport
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `)
  const insertRef = db.prepare(`
    INSERT INTO symbol_refs (
      ref_id, file_path, symbol_name, container, ref_kind, line, col,
      target_symbol_id, target_file_path, target_symbol_uid, ref_name,
      resolution_kind, resolution_confidence, resolution_strategy,
      parser_tier, parser_confidence
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `)
  const insertCallEdge = db.prepare(`
    INSERT INTO call_edges (
      edge_id, file_path, caller_symbol, callee_symbol, line, start_col,
      target_symbol_id, target_file_path, caller_symbol_id, caller_symbol_uid,
      callee_symbol_uid, dispatch_kind, call_kind, resolution_kind,
      resolution_confidence, resolution_strategy, receiver_expr, arg_count,
      is_optional_chain, is_awaited, is_constructor, parser_tier, parser_confidence
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `)
  const insertTestEdge = db.prepare(`
    INSERT INTO test_edges (edge_id, test_file_path, code_file_path, reason, confidence)
    VALUES (?, ?, ?, ?, ?)
  `)
  const insertLiteral = db.prepare(`
    INSERT INTO literal_index (
      literal_id, file_path, literal, literal_kind, line, container,
      confidence, enclosing_symbol_uid
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `)
  for (const symbol of graph.symbols) {
    insertSymbol.run(
      symbol.symbolId,
      symbol.filePath,
      symbol.name,
      symbol.kind,
      symbol.container,
      symbol.startLine,
      symbol.endLine,
      symbol.startCol,
      symbol.endCol,
      symbol.signature,
      symbol.doc,
      symbol.parserTier,
      symbol.parserConfidence,
      symbol.qname,
      symbol.parentSymbolId,
      symbol.exportName,
      symbol.isDefaultExport ? 1 : 0,
      symbol.symbolUid,
      symbol.frameworkRole,
      symbol.receiverType,
      symbol.paramTypes,
      symbol.returnType,
      symbol.paramCount,
      symbol.baseTypes,
      symbol.implements,
    )
  }
  for (const row of graph.imports) {
    insertImport.run(
      row.filePath,
      row.importString,
      row.resolvedPath,
      row.importedName,
      row.alias,
      row.isNamespace ? 1 : 0,
      row.isDefault ? 1 : 0,
      row.isReexport ? 1 : 0,
    )
  }
  for (const row of graph.symbolRefs) {
    runInsertRef(insertRef, row)
  }
  for (const row of graph.callEdges) {
    runInsertCallEdge(insertCallEdge, row)
  }
  for (const row of graph.testEdges) {
    insertTestEdge.run(row.edgeId, row.testFilePath, row.codeFilePath, row.reason, row.confidence)
  }
  for (const row of graph.literals) {
    insertLiteral.run(
      row.literalId,
      row.filePath,
      row.literal,
      row.literalKind,
      row.line,
      row.container,
      row.confidence,
      row.enclosingSymbolUid,
    )
  }
  return {
    symbols: graph.symbols.length,
    callEdges: graph.callEdges.length,
    symbolRefs: graph.symbolRefs.length,
    testEdges: graph.testEdges.length,
    literals: graph.literals.length,
  }
}
